import type { Department, Lang } from "./types";

export const deptLabel: Record<Lang, Record<Department, string>> = {
  zh: { support: "客服", people: "人資", finance: "財務", ops: "營運" },
  en: { support: "Support", people: "People", finance: "Finance", ops: "Operations" },
};

export const copy = {
  brand: { zh: "智工隊", en: "Harbour Crew" },
  brandEn: "Harbour Crew",
  tagline: { zh: "建立您的企業 AI 員工團隊", en: "Build your enterprise AI staff" },
  nav: { product: { zh: "方案", en: "Product" }, console: { zh: "控制台", en: "Console" }, contact: { zh: "免費諮詢", en: "Book a consult" } },
  heroKicker: { zh: "香港中小企 · 本地部署 · AI 員工", en: "Hong Kong SMEs · on-site · AI staff" },
  heroLead: { zh: "重複行政正在吃掉團隊時間。客服、排班、對帳、報表，都可以交給可訓練、可排程、可稽核的 AI 員工。", en: "Repetitive admin is eating your team. Support, rostering, reconciliation, and reports can sit with AI staff you can train, schedule, and audit." },
  heroCta: { zh: "免費諮詢", en: "Free consult" },
  heroSecondary: { zh: "打開控制台", en: "Open console" },
  worry: {
    q: { zh: "公司想引入 AI，最常見的擔心是不是這句？", en: "Is this the line every company says before they stall?" },
    quote: { zh: "「唔想用雲端 AI。敏感檔案 upload 上去，陣間流出咗點算？」", en: "We don’t want cloud AI. If a sensitive file goes up, what happens when it leaks?" },
    label: { zh: "擔心一：公司數據私隱", en: "Worry 1: company data leaving the office" },
  },
  whyTitle: { zh: "為何選擇 Harbour Crew？", en: "Why Harbour Crew?" },
  whyLead: { zh: "我們不是再賣一個聊天框。我們把 AI 員工、本地硬體、流程諮詢和系統對接做成一套可落地的方案。", en: "This is not another chatbot. It is AI staff, on-site hardware, process consulting, and system hooks as one deployable stack." },
  why: [
    { n: "01", title: { zh: "辦公室裡的 AI 伺服器", en: "An AI node in the office" }, body: { zh: "Crew Node 放在你的辦公室，資料留在內網。平台已內建沙盒，限制每個 AI 員工能看、能改、能對外發送的範圍。", en: "Crew Node lives in your office. Data stays on the LAN. A sandbox limits what each AI employee can read, change, or send." } },
    { n: "02", title: { zh: "專人了解流程，再設置員工", en: "We learn the process, then staff it" }, body: { zh: "第一次會到場拆解部門工序。之後每月持續加技能、加排程，讓營運進步看得到。", en: "We map each department’s work on site. Every month we add skills and schedules so the operation actually moves." } },
    { n: "03", title: { zh: "現有系統免費對接", en: "Hook your current stack" }, body: { zh: "電郵、WhatsApp、常見 ERP / CRM / 會計系統可走 API。", en: "Email, WhatsApp, and common ERP / CRM / accounting tools go through APIs." } },
    { n: "04", title: { zh: "行業員工可即插即用", en: "Industry staff, ready to hire" }, body: { zh: "市集提供客服、人資、財務、營運預建員工。", en: "The market ships support, people, finance, and ops staff." } },
  ],
  caseKicker: { zh: "應用案例 01 · 餐飲集團", en: "Case 01 · restaurant group" },
  caseTitle: { zh: "以前每天花數小時排更，而家一分鐘有初稿。", en: "Rosters that took hours now draft in a minute." },
  caseQuote: { zh: "「以前要人手對齊每位廚師、侍應嘅休假同檔期。而家人資員工會讀齊出勤規則同每週班次，自動提出可上班表。」", en: "People staff now reads the rules and weekly covers, drafts a legal roster, and managers only clear conflicts." },
  caseMeta: { zh: "人資員工 · 廚房與樓面編更", en: "People staff · kitchen and floor rostering" },
  localTitle: { zh: "本地團隊、本地部署、本地支援", en: "Local team, local deploy, local support" },
  localLead: { zh: "硬體選型、平台設置、到場諮詢、之後的技術支援，全部由香港團隊跟進。", en: "Hardware, platform, on-site consulting, and support stay with a Hong Kong team." },
  stepsTitle: { zh: "下一步", en: "What happens next" },
  steps: [
    { zh: "企業填寫查詢表格", en: "You send an inquiry" },
    { zh: "專人致電初步了解", en: "We call and scope the work" },
    { zh: "到訪介紹方案，拆解真實工序", en: "On-site demo against real processes" },
    { zh: "用一條真實流程設置 AI 員工試用", en: "Stand up one live trial employee" },
    { zh: "正式採購與部署，最快一個月啟用", en: "Purchase and go live, often within a month" },
  ],
  stepsCta: { zh: "立即查詢", en: "Inquire now" },
  footerNote: { zh: "Harbour Crew 是獨立產品，不是 Praxis Claw 的官方網站或關聯公司。", en: "Harbour Crew is an independent product, not affiliated with Praxis Claw." },
  solutionHero: {
    kicker: { zh: "軟硬體一體", en: "Hardware + platform" },
    title: { zh: "把運算鎖在辦公室，把員工放進同一個介面。", en: "Lock compute in the office. Run staff in one console." },
    lead: { zh: "從精巧的邊緣硬體，到部門主管都用得懂的控制台。", en: "From a quiet edge box to a console any department lead can run." },
  },
  hardwareTitle: { zh: "Crew Node：把 AI 鎖在辦公室裡", en: "Crew Node: keep AI in the building" },
  hardwareLead: { zh: "擺脫公有雲傳輸的不確定性。企業級晶片、低噪音機身、可串聯擴容。", en: "Skip the uncertainty of public-cloud hops. Enterprise chips, quiet chassis, stackable nodes." },
  hardwarePoints: [
    { zh: "多個 AI 員工可並行，全日處理排程任務", en: "Several AI staff can run in parallel, all day" },
    { zh: "辦公室可接受的功耗與噪音", en: "Power and noise that belong in an office" },
    { zh: "業務增長時加節點", en: "Add nodes as the load grows" },
    { zh: "斷外網仍可讀內網系統", en: "Keeps reading LAN systems if the WAN drops" },
  ],
  compareTitle: { zh: "與雲端方案比", en: "Against a cloud chatbot" },
  compareHead: { dim: { zh: "評估", en: "Lens" }, us: { zh: "Harbour Crew（本地）", en: "Harbour Crew (on-site)" }, them: { zh: "傳統雲端 AI", en: "Typical cloud AI" } },
  compareRows: [
    { dim: { zh: "資料安全", en: "Data" }, us: { zh: "檔案留在辦公室，可全離線", en: "Files stay on site, can run offline" }, them: { zh: "要上傳", en: "Upload required" } },
    { dim: { zh: "延遲", en: "Latency" }, us: { zh: "內網毫秒級", en: "LAN-speed" }, them: { zh: "受外網影響", en: "Depends on WAN" } },
    { dim: { zh: "成本", en: "Cost" }, us: { zh: "硬體買斷 + 固定授權", en: "Appliance + a fixed licence" }, them: { zh: "按用量計費", en: "Token bills" } },
    { dim: { zh: "整合", en: "Integrations" }, us: { zh: "內網直連", en: "Inside the firewall" }, them: { zh: "要對外開放接口", en: "Needs outbound holes" } },
  ],
  platformTitle: { zh: "一個介面，管一整隊 AI 員工", en: "One console for the whole staff" },
  platformLead: { zh: "不需要 IT 背景。", en: "No IT degree required." },
  platform: [
    { title: { zh: "權限", en: "Access" }, body: { zh: "財務員工只有財務看見。", en: "Finance staff stays with finance." } },
    { title: { zh: "知識", en: "Knowledge" }, body: { zh: "上載 SOP、價目、合約摘要。", en: "Upload SOPs, price lists, contract notes." } },
    { title: { zh: "排程", en: "Schedules" }, body: { zh: "設定一次，每天自動跑。", en: "Set once, run every day." } },
    { title: { zh: "稽核", en: "Audit" }, body: { zh: "對話、指令、檔案全部可回溯。", en: "Chats, commands, file moves are replayable." } },
  ],
  marketTitle: { zh: "預建員工，上線再微調", en: "Hire prebuilt staff, then tune" },
  marketLead: { zh: "先選職務，再匯入公司文件。", en: "Pick a role, then import your files." },
  scenesTitle: { zh: "真實工序，不是示範片", en: "Real work, not a demo reel" },
  scenes: [
    { title: { zh: "零售排班", en: "Retail rostering" }, body: { zh: "按人流、促銷、可用性排出班表。", en: "Rosters from footfall, promos, and availability." } },
    { title: { zh: "WhatsApp 客服", en: "WhatsApp support" }, body: { zh: "24/7 用產品庫與 FAQ 回覆。", en: "Answers from the catalogue and FAQ around the clock." } },
    { title: { zh: "費用異常", en: "Expense exceptions" }, body: { zh: "每日讀會計系統，標出異常支出。", en: "Reads the ledger daily, flags outliers." } },
    { title: { zh: "KPI 看守", en: "KPI watch" }, body: { zh: "指標越線就警示。", en: "Alerts when a metric leaves the band." } },
  ],
  contactHero: {
    title: { zh: "準備好讓 AI 員工上線？", en: "Ready to put AI staff on the floor?" },
    lead: { zh: "今天提交查詢，我們會在 1–2 個工作天內回覆。", en: "Send an inquiry today. We reply in 1–2 working days." },
  },
  form: {
    company: { zh: "企業名稱", en: "Company" },
    industry: { zh: "行業", en: "Industry" },
    name: { zh: "聯絡人", en: "Name" },
    phone: { zh: "電話", en: "Phone" },
    email: { zh: "電郵", en: "Email" },
    message: { zh: "想先處理邊條工序？", en: "Which process should we start with?" },
    submit: { zh: "提交查詢", en: "Send inquiry" },
    thanks: { zh: "已收到。這是示範站，查詢會留在你的瀏覽器控制台紀錄。", en: "Received. This is a demo — the inquiry stays in your console log." },
  },
  console: {
    team: { zh: "AI 員工團隊", en: "AI staff" },
    hire: { zh: "聘用員工", en: "Hire staff" },
    talk: { zh: "對話", en: "Talk" },
    schedule: { zh: "排程", en: "Schedule" },
    files: { zh: "檔案", en: "Files" },
    integrations: { zh: "系統", en: "Systems" },
    market: { zh: "市集", en: "Market" },
    audit: { zh: "稽核", en: "Audit" },
    overview: { zh: "今日概況", en: "Today" },
    online: { zh: "在線", en: "Online" },
    jobs: { zh: "已排程任務", en: "Scheduled jobs" },
    filesCount: { zh: "知識檔案", en: "Knowledge files" },
    chatHint: { zh: "用粵語或英文下指令。", en: "Brief in Cantonese or English." },
    send: { zh: "發送", en: "Send" },
    skills: { zh: "技能", en: "Skills" },
    knowledge: { zh: "知識", en: "Knowledge" },
    addSkill: { zh: "新增技能", en: "Add skill" },
    addFile: { zh: "加入檔案摘要", en: "Add file note" },
    addJob: { zh: "新增排程", en: "Add schedule" },
    deploy: { zh: "部署到團隊", en: "Deploy to team" },
    connect: { zh: "連接", en: "Connect" },
    connected: { zh: "已連接", en: "Connected" },
    emptyChat: { zh: "這位員工已準備好。直接講你想完成的工序。", en: "This employee is ready. Tell them the job." },
  },
} as const;
